spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:subflow}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  activiti:
    database-schema-update: true

subflow:
  bcrypt:
    iterations: 10
server:
  port: ${SUBFLOW_PORT:8080}
logging:
  level:
    com.pmrfansub.subflow: debug